# Generated by Django 5.2.1 on 2025-05-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
    ]
