# Generated by Django 5.2.1 on 2025-05-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_album_track_delete_tune'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='author',
            new_name='artist',
        ),
    ]
