# Generated by Django 5.2.1 on 2025-05-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_author_track_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to='tracks/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(upload_to='covers/'),
        ),
    ]
